# 1. IDENTIDAD DEL MICROSERVICIO
spring.application.name=hotel
server.port=8082

# LA LÍNEA QUE FALTA (Para corregir el error actual)
# Le decimos al microservicio cuál es su propia dirección
server.url=http://localhost:8082

# 2. CONEXIÓN LOCAL A TU MYSQL (Workbench)
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/db_hotelsbook?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. CONFIGURACIÓN DE JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 4. COMUNICACIÓN ENTRE MICROSERVICIOS (Por si las moscas, dejamos estas también)
microservice.services.url=http://services-ms:8080/api/hotels/services
microservice.reviews.url=http://reviews-ms:8081/api/hotels/reviews

